#pragma once

#define IOCTL_INJECT_ALLOC  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INJECT_EXEC   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_MEMORY  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PID      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_BASE     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FIND_PID     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _INJECT_ALLOC_REQUEST {
    HANDLE ProcessId;
    SIZE_T SizeOfImage;
    PVOID RemoteBase;
    NTSTATUS ErrorStatus;
} INJECT_ALLOC_REQUEST, * PINJECT_ALLOC_REQUEST;

typedef struct _INJECT_EXEC_REQUEST {
    HANDLE ProcessId;
    PVOID RemoteBase;
    NTSTATUS ErrorStatus;
} INJECT_EXEC_REQUEST, * PINJECT_EXEC_REQUEST;

typedef struct _MEMORY_REQUEST {
    HANDLE ProcessId;
    ULONG_PTR Address;
    PVOID Buffer;
    SIZE_T Size;
} MEMORY_REQUEST, * PMEMORY_REQUEST;
